require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoursController do

  # This should return the minimal set of attributes required to create a valid
  # Cour. As you add validations to Cour, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoursController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cours as @cours" do
      cour = Cour.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cours).should eq([cour])
    end
  end

  describe "GET show" do
    it "assigns the requested cour as @cour" do
      cour = Cour.create! valid_attributes
      get :show, {:id => cour.to_param}, valid_session
      assigns(:cour).should eq(cour)
    end
  end

  describe "GET new" do
    it "assigns a new cour as @cour" do
      get :new, {}, valid_session
      assigns(:cour).should be_a_new(Cour)
    end
  end

  describe "GET edit" do
    it "assigns the requested cour as @cour" do
      cour = Cour.create! valid_attributes
      get :edit, {:id => cour.to_param}, valid_session
      assigns(:cour).should eq(cour)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cour" do
        expect {
          post :create, {:cour => valid_attributes}, valid_session
        }.to change(Cour, :count).by(1)
      end

      it "assigns a newly created cour as @cour" do
        post :create, {:cour => valid_attributes}, valid_session
        assigns(:cour).should be_a(Cour)
        assigns(:cour).should be_persisted
      end

      it "redirects to the created cour" do
        post :create, {:cour => valid_attributes}, valid_session
        response.should redirect_to(Cour.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cour as @cour" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cour.any_instance.stub(:save).and_return(false)
        post :create, {:cour => {}}, valid_session
        assigns(:cour).should be_a_new(Cour)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cour.any_instance.stub(:save).and_return(false)
        post :create, {:cour => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cour" do
        cour = Cour.create! valid_attributes
        # Assuming there are no other cours in the database, this
        # specifies that the Cour created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cour.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cour.to_param, :cour => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cour as @cour" do
        cour = Cour.create! valid_attributes
        put :update, {:id => cour.to_param, :cour => valid_attributes}, valid_session
        assigns(:cour).should eq(cour)
      end

      it "redirects to the cour" do
        cour = Cour.create! valid_attributes
        put :update, {:id => cour.to_param, :cour => valid_attributes}, valid_session
        response.should redirect_to(cour)
      end
    end

    describe "with invalid params" do
      it "assigns the cour as @cour" do
        cour = Cour.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cour.any_instance.stub(:save).and_return(false)
        put :update, {:id => cour.to_param, :cour => {}}, valid_session
        assigns(:cour).should eq(cour)
      end

      it "re-renders the 'edit' template" do
        cour = Cour.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cour.any_instance.stub(:save).and_return(false)
        put :update, {:id => cour.to_param, :cour => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cour" do
      cour = Cour.create! valid_attributes
      expect {
        delete :destroy, {:id => cour.to_param}, valid_session
      }.to change(Cour, :count).by(-1)
    end

    it "redirects to the cours list" do
      cour = Cour.create! valid_attributes
      delete :destroy, {:id => cour.to_param}, valid_session
      response.should redirect_to(cours_url)
    end
  end

end
